### ISSUE TITLE
Players can see setup 

### ISSUE THREAD

**Issue by EoinMan** [foundry-vtt-community/foundry-vtt-community.github.io#1]
Hello 

I was looking where to create issues and was unable to find it. 

When hosting a world with a player they can see /setup

To reproduce 

1) Load world with player 
2) Exit world, leave player in world 
3) Enter world again
4) Have player refresh screen 

player is now defaulted to /setup

If you need more information or if I am missing a setup please message me

**Comment by EoinMan** [comment]
User Error
Mb

**Comment by kakaroto** [comment]
Definitely not the right place to report issues, also you don't seem to understand how Foundry works. In this case, you're either restarting your server, or you're clicking "return to setup". Make sure you set an admin access key to prevent unauthorized access to the setup page, if you don't want someone to stumble on it and delete it all.
I suggest you join the official Discord, it's a better place to connect with the community and learn about the software. https://discordapp.com/invite/DDBZUDf
